#Initialization

In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Stunted Children Identification/stunting-identification-lab

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Stunted Children Identification/stunting-identification-lab

In [2]:
import pandas as pd

In [3]:
base = "/content/drive/MyDrive/Stunted Children Identification/stunting-identification-lab/result/"
metrics = ['accuracy', 'precision', 'sensitivity', 'specificity', 'f1', 'f2']

#Sc.1. Result Preview

In [4]:
sc1_train_result_df = pd.read_excel(base + 'sc1_train_result.xlsx')
sc1_result_df       = pd.read_excel(base + 'sc1_result.xlsx')

sc1_test_result_df          = sc1_result_df[sc1_result_df.evaluation == "test"]
sc1_test_result_df[metrics] = sc1_test_result_df[metrics] * 100

sc1_summary_test_df = pd.merge(sc1_train_result_df,
                               sc1_test_result_df,
                               on=['model_name', 'scheme', 'model', 'optimizer'],
                               how='inner')

sc1_summary_test_df = sc1_summary_test_df.loc[:,
 ["scheme", "model", "optimizer", "best_epoch", "sensitivity", "specificity", "f2"]]

/tmp/ipykernel_8050/48753811.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sc1_test_result_df[metrics] = sc1_test_result_df[metrics] * 100

In [5]:
sc1_summary_test_df.round(2)

,scheme,model,optimizer,best_epoch,sensitivity,specificity,f2
0,sc1a,efficientnet-b0,sgd,19,100.0,100.0,100.00
1,sc1a,efficientnet-b0,adam,19,100.0,100.0,100.00
2,sc1a,efficientnet-b0,adamw,19,100.0,100.0,100.00
3,sc1b,efficientnet-b0,sgd,7,64.5,71.0,65.35
4,sc1b,efficientnet-b0,adam,10,80.0,67.0,77.97
5,sc1b,efficientnet-b0,adamw,10,80.0,66.5,77.90

#Sc.2. Result Preview

In [6]:
sc2_train_result_df = pd.read_excel(base + 'sc2_train_result.xlsx')
sc2_result_df       = pd.read_excel(base + 'sc2_result.xlsx')

sc2_test_result_df          = sc2_result_df[sc2_result_df.evaluation == "test"]
sc2_test_result_df[metrics] = sc2_test_result_df[metrics] * 100

sc2_summary_test_df = pd.merge(sc2_train_result_df,
                               sc2_test_result_df,
                               on=['model_name', 'scheme', 'model', 'optimizer'],
                               how='inner')

sc2_summary_test_df = sc2_summary_test_df.loc[:,
 ["scheme", "model", "optimizer", "best_epoch", "sensitivity", "specificity", "f2"]]

/tmp/ipykernel_8050/3279705260.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sc2_test_result_df[metrics] = sc2_test_result_df[metrics] * 100

In [7]:
sc2_summary_test_df.round(2)

,scheme,model,optimizer,best_epoch,sensitivity,specificity,f2
0,sc2a,efficientnet-b0,sgd,2,70.0,40.0,66.04
1,sc2a,efficientnet-b0,adam,9,55.0,55.0,55.00
2,sc2a,efficientnet-b0,adamw,9,55.0,55.0,55.00
3,sc2b,efficientnet-b0,sgd,9,40.0,60.0,41.67
4,sc2b,efficientnet-b0,adam,8,40.0,60.0,41.67
5,sc2b,efficientnet-b0,adamw,8,40.0,60.0,41.67

#Sc.3. Result Preview

In [8]:
sc3_train_result_df = pd.read_excel(base + 'sc3_train_result.xlsx')
sc3_result_df       = pd.read_excel(base + 'sc3_result.xlsx')

sc3_test_result_df          = sc3_result_df[sc3_result_df.evaluation == "test"]
sc3_test_result_df[metrics] = sc3_test_result_df[metrics] * 100

sc3_summary_test_df = pd.merge(sc3_train_result_df,
                               sc3_test_result_df,
                               on=['model_name', 'scheme', 'model', 'optimizer'],
                               how='inner')

sc3_summary_test_df = sc3_summary_test_df.loc[:,
 ["scheme", "model", "optimizer", "best_epoch", "sensitivity", "specificity", "f2"]]

/tmp/ipykernel_8050/874718726.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sc3_test_result_df[metrics] = sc3_test_result_df[metrics] * 100

In [9]:
sc3_summary_test_df.round(2)

,scheme,model,optimizer,best_epoch,sensitivity,specificity,f2
0,sc3,efficientnet-b0,sgd,1,80.0,40.0,74.07
1,sc3,efficientnet-b0,adam,9,100.0,20.0,86.21
2,sc3,efficientnet-b0,adamw,9,60.0,20.0,55.56

#Sc.4. Result Preview

In [10]:
sc4_train_result_df = pd.read_excel(base + 'sc4_train_result.xlsx')
sc4_result_df       = pd.read_excel(base + 'sc4_result.xlsx')

sc4_test_result_df          = sc4_result_df[sc4_result_df.evaluation == "test"]
sc4_test_result_df[metrics] = sc4_test_result_df[metrics] * 100

sc4_summary_test_df = pd.merge(sc4_train_result_df,
                               sc4_test_result_df,
                               on=['model_name', 'scheme', 'model', 'optimizer'],
                               how='inner')

sc4_summary_test_df = sc4_summary_test_df.loc[:,
 ["scheme", "model", "optimizer", "best_epoch", "sensitivity", "specificity", "f2"]]

/tmp/ipykernel_8050/598285180.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sc4_test_result_df[metrics] = sc4_test_result_df[metrics] * 100

In [11]:
sc4_summary_test_df.round(2)

,scheme,model,optimizer,best_epoch,sensitivity,specificity,f2
0,sc4a,efficientnet-b0,sgd,12,75.0,36.36,66.67
1,sc4a,efficientnet-b0,adam,3,62.5,45.45,58.14
2,sc4a,efficientnet-b0,adamw,3,62.5,45.45,58.14
3,sc4b,efficientnet-b0,sgd,1,75.0,36.36,66.67
4,sc4b,efficientnet-b0,adam,3,87.5,0.00,70.00
5,sc4b,efficientnet-b0,adamw,3,87.5,0.00,70.00

#1\. Wihtin Correlation Sensitivity Analaysis

In [12]:
sensitivity_analysis_df_1 = pd.merge(sc1_summary_test_df[sc1_summary_test_df.scheme == "sc1a"],
                                     sc1_summary_test_df[sc1_summary_test_df.scheme == "sc1b"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc1a", "_sc1b")
                                     ).round(2)

sensitivity_analysis_df_1["f2_diff"]     = sensitivity_analysis_df_1["f2_sc1a"] - sensitivity_analysis_df_1["f2_sc1b"]
sensitivity_analysis_df_1["f2_diff_pct"] = (sensitivity_analysis_df_1["f2_sc1a"] - sensitivity_analysis_df_1["f2_sc1b"]) / sensitivity_analysis_df_1["f2_sc1a"] * 100
sensitivity_analysis_df_1["f2_diff_pct"] = sensitivity_analysis_df_1["f2_diff_pct"].round(2)

sensitivity_analysis_df_1.drop(columns=['scheme_sc1a', 'scheme_sc1b'])

,model,optimizer,best_epoch_sc1a,sensitivity_sc1a,specificity_sc1a,f2_sc1a,best_epoch_sc1b,sensitivity_sc1b,specificity_sc1b,f2_sc1b,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,19,100.0,100.0,100.0,7,64.5,71.0,65.35,34.65,34.65
1,efficientnet-b0,adam,19,100.0,100.0,100.0,10,80.0,67.0,77.97,22.03,22.03
2,efficientnet-b0,adamw,19,100.0,100.0,100.0,10,80.0,66.5,77.90,22.10,22.10

#2\. Pseudo-capture Sensitivity Analysis

In [13]:
sensitivity_analysis_df_2 = pd.merge(sc1_summary_test_df[sc1_summary_test_df.scheme == "sc1b"],
                                     sc2_summary_test_df[sc2_summary_test_df.scheme == "sc2a"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc1b", "_sc2a")
                                     ).round(2)

sensitivity_analysis_df_2["f2_diff"]     = sensitivity_analysis_df_2["f2_sc1b"] - sensitivity_analysis_df_2["f2_sc2a"]
sensitivity_analysis_df_2["f2_diff_pct"] = (sensitivity_analysis_df_2["f2_sc1b"] - sensitivity_analysis_df_2["f2_sc2a"]) / sensitivity_analysis_df_2["f2_sc1b"] * 100
sensitivity_analysis_df_2["f2_diff_pct"] = sensitivity_analysis_df_2["f2_diff_pct"].round(2)

sensitivity_analysis_df_2.drop(columns=['scheme_sc1b', 'scheme_sc2a'])

,model,optimizer,best_epoch_sc1b,sensitivity_sc1b,specificity_sc1b,f2_sc1b,best_epoch_sc2a,sensitivity_sc2a,specificity_sc2a,f2_sc2a,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,7,64.5,71.0,65.35,2,70.0,40.0,66.04,-0.69,-1.06
1,efficientnet-b0,adam,10,80.0,67.0,77.97,9,55.0,55.0,55.00,22.97,29.46
2,efficientnet-b0,adamw,10,80.0,66.5,77.90,9,55.0,55.0,55.00,22.90,29.40

#3\. Evaluation-set Augmentation Sensitivity Analysis

In [14]:
sensitivity_analysis_df_3 = pd.merge(sc2_summary_test_df[sc2_summary_test_df.scheme == "sc2a"],
                                     sc2_summary_test_df[sc2_summary_test_df.scheme == "sc2b"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc2a", "_sc2b")
                                     ).round(2)

sensitivity_analysis_df_3["f2_diff"]     = sensitivity_analysis_df_3["f2_sc2a"] - sensitivity_analysis_df_3["f2_sc2b"]
sensitivity_analysis_df_3["f2_diff_pct"] = (sensitivity_analysis_df_3["f2_sc2a"] - sensitivity_analysis_df_3["f2_sc2b"]) / sensitivity_analysis_df_3["f2_sc2a"] * 100
sensitivity_analysis_df_3["f2_diff_pct"] = sensitivity_analysis_df_3["f2_diff_pct"].round(2)

sensitivity_analysis_df_3.drop(columns=['scheme_sc2a', 'scheme_sc2b']).round(2)

,model,optimizer,best_epoch_sc2a,sensitivity_sc2a,specificity_sc2a,f2_sc2a,best_epoch_sc2b,sensitivity_sc2b,specificity_sc2b,f2_sc2b,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,2,70.0,40.0,66.04,9,40.0,60.0,41.67,24.37,36.90
1,efficientnet-b0,adam,9,55.0,55.0,55.00,8,40.0,60.0,41.67,13.33,24.24
2,efficientnet-b0,adamw,9,55.0,55.0,55.00,8,40.0,60.0,41.67,13.33,24.24

#4\. Training-Set Augmentation Sensitivity Analysis

In [15]:
sensitivity_analysis_df_4 = pd.merge(sc2_summary_test_df[sc2_summary_test_df.scheme == "sc2b"],
                                     sc3_summary_test_df[sc3_summary_test_df.scheme == "sc3"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc2b", "_sc3")
                                     ).round(2)

sensitivity_analysis_df_4["f2_diff"]     = sensitivity_analysis_df_4["f2_sc2b"] - sensitivity_analysis_df_4["f2_sc3"]
sensitivity_analysis_df_4["f2_diff_pct"] = (sensitivity_analysis_df_4["f2_sc2b"] - sensitivity_analysis_df_4["f2_sc3"]) / sensitivity_analysis_df_4["f2_sc2b"] * 100
sensitivity_analysis_df_4["f2_diff_pct"] = sensitivity_analysis_df_4["f2_diff_pct"].round(2)

sensitivity_analysis_df_4.drop(columns=['scheme_sc2b', 'scheme_sc3'])

,model,optimizer,best_epoch_sc2b,sensitivity_sc2b,specificity_sc2b,f2_sc2b,best_epoch_sc3,sensitivity_sc3,specificity_sc3,f2_sc3,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,9,40.0,60.0,41.67,1,80.0,40.0,74.07,-32.40,-77.75
1,efficientnet-b0,adam,8,40.0,60.0,41.67,9,100.0,20.0,86.21,-44.54,-106.89
2,efficientnet-b0,adamw,8,40.0,60.0,41.67,9,60.0,20.0,55.56,-13.89,-33.33

#5\. Class Distribution Sensitivity Analysis

In [16]:
sensitivity_analysis_df_5 = pd.merge(sc3_summary_test_df[sc3_summary_test_df.scheme == "sc3"],
                                     sc4_summary_test_df[sc4_summary_test_df.scheme == "sc4b"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc3", "_sc4b")
                                     ).round(2)

sensitivity_analysis_df_5["f2_diff"]     = sensitivity_analysis_df_5["f2_sc3"] - sensitivity_analysis_df_5["f2_sc4b"]
sensitivity_analysis_df_5["f2_diff_pct"] = (sensitivity_analysis_df_5["f2_sc3"] - sensitivity_analysis_df_5["f2_sc4b"]) / sensitivity_analysis_df_5["f2_sc3"] * 100
sensitivity_analysis_df_5["f2_diff_pct"] = sensitivity_analysis_df_5["f2_diff_pct"].round(2)

sensitivity_analysis_df_5.drop(columns=['scheme_sc3', 'scheme_sc4b'])

,model,optimizer,best_epoch_sc3,sensitivity_sc3,specificity_sc3,f2_sc3,best_epoch_sc4b,sensitivity_sc4b,specificity_sc4b,f2_sc4b,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,1,80.0,40.0,74.07,1,75.0,36.36,66.67,7.40,9.99
1,efficientnet-b0,adam,9,100.0,20.0,86.21,3,87.5,0.00,70.00,16.21,18.80
2,efficientnet-b0,adamw,9,60.0,20.0,55.56,3,87.5,0.00,70.00,-14.44,-25.99

#6\. Augmented Class Distribution Sensitivity Analysis

In [17]:
sensitivity_analysis_df_6 = pd.merge(sc3_summary_test_df[sc3_summary_test_df.scheme == "sc3"],
                                     sc4_summary_test_df[sc4_summary_test_df.scheme == "sc4a"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc3", "_sc4a")
                                     ).round(2)

sensitivity_analysis_df_6["f2_diff"]     = sensitivity_analysis_df_6["f2_sc3"] - sensitivity_analysis_df_6["f2_sc4a"]
sensitivity_analysis_df_6["f2_diff_pct"] = (sensitivity_analysis_df_6["f2_sc3"] - sensitivity_analysis_df_6["f2_sc4a"]) / sensitivity_analysis_df_6["f2_sc3"] * 100
sensitivity_analysis_df_6["f2_diff_pct"] = sensitivity_analysis_df_6["f2_diff_pct"].round(2)

sensitivity_analysis_df_6.drop(columns=['scheme_sc3', 'scheme_sc4a'])

,model,optimizer,best_epoch_sc3,sensitivity_sc3,specificity_sc3,f2_sc3,best_epoch_sc4a,sensitivity_sc4a,specificity_sc4a,f2_sc4a,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,1,80.0,40.0,74.07,12,75.0,36.36,66.67,7.40,9.99
1,efficientnet-b0,adam,9,100.0,20.0,86.21,3,62.5,45.45,58.14,28.07,32.56
2,efficientnet-b0,adamw,9,60.0,20.0,55.56,3,62.5,45.45,58.14,-2.58,-4.64

#7\. Augmented Natural Distribution Sensitivity Analysis

In [18]:
sensitivity_analysis_df_7 = pd.merge(sc4_summary_test_df[sc4_summary_test_df.scheme == "sc4a"],
                                     sc4_summary_test_df[sc4_summary_test_df.scheme == "sc4b"],
                                     on=['model', 'optimizer'],
                                     how='inner',
                                     suffixes=("_sc4a", "_sc4b")
                                     ).round(2)

sensitivity_analysis_df_7["f2_diff"]     = sensitivity_analysis_df_7["f2_sc4a"] - sensitivity_analysis_df_7["f2_sc4b"]
sensitivity_analysis_df_7["f2_diff_pct"] = (sensitivity_analysis_df_7["f2_sc4a"] - sensitivity_analysis_df_7["f2_sc4b"]) / sensitivity_analysis_df_7["f2_sc4a"] * 100
sensitivity_analysis_df_7["f2_diff_pct"] = sensitivity_analysis_df_7["f2_diff_pct"].round(2)

sensitivity_analysis_df_7.drop(columns=['scheme_sc4a', 'scheme_sc4b']).round(2)

,model,optimizer,best_epoch_sc4a,sensitivity_sc4a,specificity_sc4a,f2_sc4a,best_epoch_sc4b,sensitivity_sc4b,specificity_sc4b,f2_sc4b,f2_diff,f2_diff_pct
0,efficientnet-b0,sgd,12,75.0,36.36,66.67,1,75.0,36.36,66.67,0.00,0.0
1,efficientnet-b0,adam,3,62.5,45.45,58.14,3,87.5,0.00,70.00,-11.86,-20.4
2,efficientnet-b0,adamw,3,62.5,45.45,58.14,3,87.5,0.00,70.00,-11.86,-20.4